# Generated by Django 4.2.11 on 2024-05-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vendor', '0009_alter_purchaseorder_quality_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='acknowledgment_date',
            new_name='acknowledgement_date',
        ),
    ]
